### PR TITLE
Dev 1

### PR DESCRIPTION
**Pull request by Thendo-T**
haven't started yet. just setting up.
wanted to add tailwind to make styling easier, though I thought I should run it by you before I do anything. by the way, are you building a network speed tester?

### CODE REVIEW

**Comment by losier** [comment]
@Thendo-T i guess you used npm to install some dependencies its in yarn so it goona send some warn in console i guess

**Comment by Thendo-T** [comment]
thought you used npm. I'll use yarn now

**Comment by losier** [comment]
Or tell me the dependise you need I'll install for you and push if you want

**Comment by Thendo-T** [comment]
I normally use npm so, that's about all I need for now.

**Comment by losier** [comment]
Ohh then lets shift to nom delete yarn.lock n do nom install we will all set to go...

**Comment by Thendo-T** [comment]
cool

**Comment by Thendo-T** [comment]
What's your Discord Username?

**Comment by Thendo-T** [comment]
you can delete your reply after a replying

**Comment by Thendo-T** [comment]
Just sent a friend request

**Pull request closed without merging**
